In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\feggi\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\feggi\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\feggi\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\feggi\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\feggi\anaconda3\lib\site-packages (from requests) (2026.5.20)

In [6]:
import requests
import pandas as pd
from datetime import datetime

In [7]:
API_KEY = "d574d6f14e5875972b2394829b447734"

In [8]:
cities = [
    "Lagos",
    "Warri",
    "Ibadan",
    "Abuja",
    "Benin",
    "Port Harcourt",
    "Onitsha",
    "Enugu",
    "Zaria",
    "Jos"
]

In [31]:
weather_data = []

for city in cities:

    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

    response = requests.get(url)

    data = response.json()

    weather_data.append({
        "City Name": data["name"],
        "Temperature": data["main"]["temp"],
        "Humidity": data["main"]["humidity"],
        "Weather Condition": data["weather"][0]["description"],
        "Wind Speed": data["wind"]["speed"],
        "Date and Time": datetime.fromtimestamp(data["dt"])
    })
print(" Raw weather data successfully extracted from the API.")

 Raw weather data successfully extracted from the API.

In [32]:
weather_data

[{'City Name': 'Lagos',
  'Temperature': 26.11,
  'Humidity': 86,
  'Weather Condition': 'moderate rain',
  'Wind Speed': 2.28,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 0, 43)},
 {'City Name': 'Warri',
  'Temperature': 26.73,
  'Humidity': 80,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 2.83,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 36)},
 {'City Name': 'Ibadan',
  'Temperature': 25.25,
  'Humidity': 86,
  'Weather Condition': 'moderate rain',
  'Wind Speed': 2.07,
  'Date and Time': datetime.datetime(2026, 7, 14, 9, 59, 19)},
 {'City Name': 'Abuja',
  'Temperature': 24.38,
  'Humidity': 87,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 1.61,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 6)},
 {'City Name': 'Benin',
  'Temperature': 26.32,
  'Humidity': 76,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 3.54,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 40)},
 {'City Name': 'Port Harcourt',
  'Temperature': 25.01,
  'Humidity': 87,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 1.97,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 42)},
 {'City Name': 'Onitsha',
  'Temperature': 24.71,
  'Humidity': 91,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 1.72,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 43)},
 {'City Name': 'Enugu',
  'Temperature': 22.83,
  'Humidity': 97,
  'Weather Condition': 'overcast clouds',
  'Wind Speed': 0.87,
  'Date and Time': datetime.datetime(2026, 7, 14, 9, 58, 4)},
 {'City Name': 'Zaria',
  'Temperature': 26.03,
  'Humidity': 72,
  'Weather Condition': 'broken clouds',
  'Wind Speed': 3.97,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 0, 4)},
 {'City Name': 'Jos',
  'Temperature': 23.44,
  'Humidity': 76,
  'Weather Condition': 'broken clouds',
  'Wind Speed': 0.63,
  'Date and Time': datetime.datetime(2026, 7, 14, 10, 2, 47)}]

*DATA TRANSFORMATION*

In [33]:
# Organising the data into a structure format using pandas 
df= pd.DataFrame(weather_data)

In [34]:
df.head()

,City Name,Temperature,Humidity,Weather Condition,Wind Speed,Date and Time
0,Lagos,26.11,86,moderate rain,2.28,2026-07-14 10:00:43
1,Warri,26.73,80,overcast clouds,2.83,2026-07-14 10:02:36
2,Ibadan,25.25,86,moderate rain,2.07,2026-07-14 09:59:19
3,Abuja,24.38,87,overcast clouds,1.61,2026-07-14 10:02:06
4,Benin,26.32,76,overcast clouds,3.54,2026-07-14 10:02:40

In [35]:
#Saving data 
df.to_csv("raw_weather_data.csv", index="False")
print("saved")

saved

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City Name          10 non-null     object
 1   Temperature        10 non-null     float64
 2   Humidity           10 non-null     int64
 3   Weather Condition  10 non-null     object
 4   Wind Speed         10 non-null     float64
 5   Date and Time      10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 612.0+ bytes

In [37]:
#Column Rename.
df.rename(columns={
    "City Name" : "City",
    "Weather Condition" : "Weather",
    "Wind Speed": "Wind_Speed_m/s",
    "Date and Time": "Datetime"
}, inplace = True)
print("Done")

Done

In [38]:
df.head()

,City,Temperature,Humidity,Weather,Wind_Speed_m/s,Datetime
0,Lagos,26.11,86,moderate rain,2.28,2026-07-14 10:00:43
1,Warri,26.73,80,overcast clouds,2.83,2026-07-14 10:02:36
2,Ibadan,25.25,86,moderate rain,2.07,2026-07-14 09:59:19
3,Abuja,24.38,87,overcast clouds,1.61,2026-07-14 10:02:06
4,Benin,26.32,76,overcast clouds,3.54,2026-07-14 10:02:40

In [39]:
#Capitalize Weather inputs
df["Weather"] = df["Weather"].str.title()
print("Done")

Done

In [40]:
df.tail()

,City,Temperature,Humidity,Weather,Wind_Speed_m/s,Datetime
5,Port Harcourt,25.01,87,Overcast Clouds,1.97,2026-07-14 10:02:42
6,Onitsha,24.71,91,Overcast Clouds,1.72,2026-07-14 10:02:43
7,Enugu,22.83,97,Overcast Clouds,0.87,2026-07-14 09:58:04
8,Zaria,26.03,72,Broken Clouds,3.97,2026-07-14 10:00:04
9,Jos,23.44,76,Broken Clouds,0.63,2026-07-14 10:02:47

In [43]:
#Ensure Numeric Columns
df["Temperature"] = df["Temperature"].astype(float)
df["Humidity"] = df ["Humidity"]. astype(int)
df["Wind_Speed_m/s"] = df["Wind_Speed_m/s"].astype(float)
df["Datetime"] = pd.to_datetime(df["Datetime"])
print("Cleaned and transformed the weather dataset.")

Cleaned and transformed the weather dataset.

In [44]:
df.head()

,City,Temperature,Humidity,Weather,Wind_Speed_m/s,Datetime
0,Lagos,26.11,86,Moderate Rain,2.28,2026-07-14 10:00:43
1,Warri,26.73,80,Overcast Clouds,2.83,2026-07-14 10:02:36
2,Ibadan,25.25,86,Moderate Rain,2.07,2026-07-14 09:59:19
3,Abuja,24.38,87,Overcast Clouds,1.61,2026-07-14 10:02:06
4,Benin,26.32,76,Overcast Clouds,3.54,2026-07-14 10:02:40

In [46]:
# Save cleaned dataset
df.to_csv("Cleaned_raw_weather_data.csv", index ="False")
print("Processed weather data saved successfully.")

Processed weather data saved successfully.

*ANALYSIS*

In [49]:
#Find the coolest city
Coolest = df.loc[df["Temperature"].idxmin()]
print(Coolest[["City","Temperature"]])

City           Enugu
Temperature    22.83
Name: 7, dtype: object

In [50]:
#Find the hottest city
Hottest = df.loc[df["Temperature"].idxmax()]
print(Hottest[["City", "Temperature"]])

City           Warri
Temperature    26.73
Name: 1, dtype: object

In [51]:
#Average Temperature
Average_Temp = df["Temperature"].mean()
print(f"Average Temperature: {Average_Temp:.2f} °C")

Average Temperature: 25.08 °C

In [52]:
#Compare weather conditions
df["Weather"].value_counts()

Weather
Overcast Clouds    6
Moderate Rain      2
Broken Clouds      2
Name: count, dtype: int64

In [53]:
#Compare Temperatures across cities
df[["City", "Temperature"]].sort_values(by="Temperature", ascending=False)

            City  Temperature
1          Warri        26.73
4          Benin        26.32
0          Lagos        26.11
8          Zaria        26.03
2         Ibadan        25.25
5  Port Harcourt        25.01
6        Onitsha        24.71
3          Abuja        24.38
9            Jos        23.44
7          Enugu        22.83

In [56]:
#City with the highest humidity
Highest_humidity = df.loc[df["Humidity"].idxmax()]
print(f"Highest Humidity: {Highest_Humidity}")

Highest Humidity: City                            Enugu
Temperature                     22.83
Humidity                           97
Weather               Overcast Clouds
Wind_Speed_m/s                   0.87
Datetime          2026-07-14 09:58:04
Name: 7, dtype: object